/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_kinow_testdemo_HlloNDK */

#ifndef _Included_com_example_kinow_testdemo_HlloNDK
#define _Included_com_example_kinow_testdemo_HlloNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_kinow_testdemo_HlloNDK
 * Method:    getHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_kinow_testdemo_HlloNDK_getHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
