/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_kinow_testdemo_GetDev */

#ifndef _Included_com_example_kinow_testdemo_GetDev
#define _Included_com_example_kinow_testdemo_GetDev
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_kinow_testdemo_GetDev
 * Method:    getDevice
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_kinow_testdemo_GetDev_getDevice
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
